site_name: GradsFlow
site_description: "An open-source AutoML Library in PyTorch"
copyright: 'Copyright &copy; 2021 GradsFlow'
banner_url: https://ik.imagekit.io/gradsflow/logo/logo-small_g2MxLWesD.png?updatedAt=1627716948296
repo_url: https://github.com/gradsflow/gradsflow/
repo_name: gradsflow/gradsflow

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

  logo: https://ik.imagekit.io/gradsflow/logo/logo-small_g2MxLWesD.png?updatedAt=1627716948296
  favicon: https://ik.imagekit.io/gradsflow/favicon/favicon_7lEXKqKWxlD.ico?updatedAt=1627717083206
  features:
    - search.suggest
    - search.highlight

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: "#"

plugins:
  - git-revision-date-localized
  - search
  - autorefs
  - mkdocs-jupyter
  - monorepo
  - meta-descriptions
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false

extra:
  homepage: https://docs.gradsflow.com

nav:
  - Introduction: 'index.md'
#  - Guide:
#      - Examples:
#          - Auto Image Classification: "https://github.com/gradsflow/gradsflow/blob/main/examples/nbs/01-ImageClassification.ipynb"
  - Reference:
      - Core: gradsflow/core.md
      - Auto Tasks: gradsflow/autotasks.md
      - utility: gradsflow/utility.md
  - Release Notes: 'CHANGELOG.md'
