name: Colab Badge
on: [push]


jobs:
  build:
    name: Colab Badge Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout first
        id: checkout
        uses: actions/checkout@v2

      - name: Add/Update badges
        id: badges
        uses: trsvchn/colab-badge-action@v3
        with:
          check: 'all'
          update: true
          target_branch: ''
          target_repository: ''

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
